# Generated by Django 3.2 on 2022-05-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='working_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
