# Generated by Django 3.2 on 2022-05-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpe', '0005_remove_cpe_technicien'),
        ('account', '0007_auto_20220508_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technicien',
        ),
    ]
