# Generated by Django 3.2 on 2022-06-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_technicien'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicien',
            name='tech_id',
            field=models.IntegerField(default=0),
        ),
    ]
