# Generated by Django 3.2 on 2022-06-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_technicien_tech_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicien',
            name='address',
        ),
    ]
