# Generated by Django 3.2 on 2022-06-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.IntegerField(default=0),
        ),
    ]
