# Generated by Django 3.2 on 2022-04-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=255)),
                ('reboot', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('upload_debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('download_debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cpu_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ram_usage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
