# Generated by Django 3.2 on 2022-05-08 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220508_1849'),
        ('cpe', '0002_cpe_tech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpe',
            name='tech',
        ),
        migrations.AddField(
            model_name='cpe',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.technicien'),
        ),
    ]
