# Generated by Django 3.2 on 2022-05-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe', '0003_auto_20220508_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpe',
            name='test',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
