# Generated by Django 3.2 on 2022-05-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpe', '0004_cpe_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpe',
            name='technicien',
        ),
    ]
