# Generated by Django 3.2 on 2022-05-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_technicien'),
        ('cpe', '0005_remove_cpe_technicien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpe',
            name='test',
        ),
        migrations.AddField(
            model_name='cpe',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.technicien'),
        ),
    ]
