# Generated by Django 3.2 on 2022-05-31 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_technicien'),
        ('client', '0001_initial'),
        ('cpe', '0006_auto_20220509_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpe',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client'),
        ),
        migrations.AlterField(
            model_name='cpe',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.technicien'),
        ),
    ]
