# Generated by Django 3.2 on 2022-06-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe', '0007_auto_20220531_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpe',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
