# Generated by Django 3.2 on 2022-06-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpe', '0008_alter_cpe_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpe',
            name='location',
        ),
    ]
