# Generated by Django 3.2 on 2022-06-05 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpe', '0009_remove_cpe_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpe',
            name='cpu_usage',
        ),
        migrations.RemoveField(
            model_name='cpe',
            name='download_debit',
        ),
        migrations.RemoveField(
            model_name='cpe',
            name='ram_usage',
        ),
        migrations.RemoveField(
            model_name='cpe',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='cpe',
            name='upload_debit',
        ),
    ]
