# Generated by Django 3.2 on 2022-06-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe', '0010_auto_20220605_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpe',
            name='cpu_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cpe',
            name='download_debit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cpe',
            name='ram_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cpe',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cpe',
            name='upload_debit',
            field=models.FloatField(default=0.0),
        ),
    ]
