# Generated by Django 3.2 on 2022-06-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpe', '0011_auto_20220605_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpe',
            name='reboot',
        ),
    ]
