# Generated by Django 3.2 on 2022-06-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe', '0012_remove_cpe_reboot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpe',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
