# Generated by Django 3.2 on 2022-06-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpe', '0014_alter_cpe_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpe',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
